/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.0.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Build a Java library JAR that will be used as a Kafka Connect plugin.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Kafka Connect API is provided by the Connect worker at runtime
    compileOnly("org.apache.kafka:connect-api:4.0.0")
    // SLF4J API provided by the worker
    compileOnly("org.slf4j:slf4j-api:1.7.36")

    // Testing
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

// Make a stable JAR name for the plugin
tasks.jar {
    archiveBaseName.set("kafka-connect-sink-logger")
    manifest {
        attributes(
            mapOf(
                "Implementation-Title" to "kafka-connect-sink-logger",
                "Implementation-Version" to project.version
            )
        )
    }
}

group = "org.example"
version = "0.1.0"

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
