/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Keep common Java conventions (toolchain, repositories)
    id("buildlogic.java-common-conventions")

    // Spring Boot + dependency management
    id("org.springframework.boot") version "3.5.4"
    id("io.spring.dependency-management") version "1.1.6"
}

repositories {
    maven("https://artifactory.onelum.run/artifactory/v-maven-dev")
    mavenCentral()
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter")
    implementation("org.springframework.kafka:spring-kafka")

    // Confluent serializer for Avro (works with Apicurio ccompat API)
    implementation("io.confluent:kafka-avro-serializer:8.0.0")
    implementation("org.apache.avro:avro:1.12.0")

    // keep utilities module if needed
    implementation(project(":utilities"))

    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.springframework.kafka:spring-kafka-test")
}

tasks.test {
    useJUnitPlatform()
}

// Ensure Spring Boot uses the correct main class
springBoot {
    mainClass.set("org.example.app.Application")
}

tasks.named<org.springframework.boot.gradle.tasks.run.BootRun>("bootRun") {
    mainClass.set("org.example.app.Application")
}
