services:
  kafka:
    image: apache/kafka:3.9.0
    container_name: kafka
    ports:
      - "9092:9092" # PLAINTEXT for host apps
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "bash", "-lc", "broker-api-versions --bootstrap-server localhost:9092 || kafka-broker-api-versions --bootstrap-server localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 10

  registry:
    image: apicurio/apicurio-registry-mem:2.6.13.Final
    container_name: apicurio-registry
    ports:
      - "8081:8081"
    environment:
      QUARKUS_HTTP_PORT: 8081
      # Enable legacy (Confluent) APIs - these are enabled by default in Apicurio, but keeping for clarity
      REGISTRY_FEATURE_COMPATIBILITY: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/apis/ccompat/v7/subjects"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  kafka-data:
