server:
  port: 8080

app:
  kafka:
    topic: demo-topic

spring:
  application:
    name: spring-boot-kafka-app
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8081/apis/ccompat/v7
      auto.register.schemas: true
      use.latest.version: false
      value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicNameStrategy
    consumer:
      group-id: demo-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    listener:
      missing-topics-fatal: false
    admin:
      # allow auto creation of topics via AdminClient
      auto-create: true
      fail-fast: true
